# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4036ba82e543d89783b3bb83cb81897c302d75b8b1808b5abf9c8a21dda46d14946e4b219ca5f8c54c2335a1d0e5d476f8650a601fe213950daf8f367f350666

test:
  secret_key_base: e68fe8452a4046b9ec6463ef96fe62898f4cb9a125e9a50e094533a8763e0170b801795a16a781a6feb96af159ac49d906246b3688b82dd75a6a2031554d759e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
